USE [master]
GO

/****** Object:  Database [YleanaCodingExercise]    Script Date: 11/8/2015 10:36:17 PM ******/
DROP DATABASE [YleanaCodingExercise]
GO

/****** Object:  Database [YleanaCodingExercise]    Script Date: 11/8/2015 10:36:17 PM ******/
CREATE DATABASE [YleanaCodingExercise]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YleanaCodingExercise', FILENAME = N'D:\DATA\MSSQL11.MSSQLSERVER\MSSQL\DATA\YleanaCodingExercise.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'YleanaCodingExercise_log', FILENAME = N'D:\DATA\MSSQL11.MSSQLSERVER\MSSQL\DATA\YleanaCodingExercise_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [YleanaCodingExercise] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YleanaCodingExercise].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YleanaCodingExercise] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET ARITHABORT OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [YleanaCodingExercise] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YleanaCodingExercise] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YleanaCodingExercise] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YleanaCodingExercise] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YleanaCodingExercise] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [YleanaCodingExercise] SET  MULTI_USER 
GO

ALTER DATABASE [YleanaCodingExercise] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YleanaCodingExercise] SET DB_CHAINING OFF 
GO

ALTER DATABASE [YleanaCodingExercise] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [YleanaCodingExercise] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [YleanaCodingExercise] SET  READ_WRITE 
GO


